### PR TITLE
Upgraded to 2.0.5

### PR DESCRIPTION
**Pull request by jeweloper**
Upgraded to 2.0.5

### CODE REVIEW

**Comment by cecton** [comment]
Thanks a lot @jeweloper

**Comment by cecton** [comment]
grmbl you forgot the .SRCINFO and you made a mistake in the commit message

**Comment by jeweloper** [comment]
Sry, you are right.
I think the only way to fix it, is to revert the changes and create a new commit/pull request.
Am I to do it?

**Comment by cecton** [comment]
of course not XD it's just a PKGBUILD

**Pull request merged**
